### PR TITLE
[AT] add court-like institutions and recently abolished courts

### PR DESCRIPTION
**Pull request by georgd**
Re-organise the file to list the state jurisdictions right after federal and atop regional jurisdictions

### CODE REVIEW

**Comment by fbennett** [comment]
Changes cherry-picked to master. If you would like this put up as a beta before full release, which platform would you prefer (Linux, Windows, Mac)?

**Comment by georgd** [comment]
> Changes cherry-picked to master. If you would like this put up as a beta before full release, which platform would you prefer (Linux, Windows, Mac)?

Please, I’d like it for Mac. Thank you!

**Comment by fbennett** [comment]
Dear Georg: The beta should be installable from this link:
> https://our.law.nagoya-u.ac.jp/jurism/dl?channel=beta&amp;platform=mac
Let me know how you get on!
Frank

**Comment by georgd** [comment]
Dear Frank, thanks for the link. Sadly, something’s wrong. The program starts up but the window panes stay empty. Do you have an idea what went wrong? Some access rights missing perhaps?

**Comment by fbennett** [comment]
Oh, that's not good. The code was tested in the release branch, then merged
to beta when I realized that it needed to reside there. Should be the same
code, but I didn't do  a trial to be sure it would run. Checking now, more
in a few minutes.

**Comment by fbennett** [comment]
Well, that's interesting. The Mac build fails with a low-level "Can't find
XPCOM" error, in both the beta and the release builds. The current release
linked from the project site runs fine, so something has changed between
then and now ... and this appears to be it:

https://github.com/zotero/zotero-standalone-build/commit/32c50ad266ae3b21cb320575d74b9a20195fed4a

zotero-standalone-build provides the stripped-down Firefox environment in
which Zotero (and Jurism) runs. The note seems to be saying that to chase
the latest Mac compatibility fixes, I'll need to build Firefox from scratch
to obtain the Mac libraries. I've done that before (at the last major MacOS
version threshold), and it takes something like six hours on my equipment.
So ... this will happen, but it might not happen fast.

**Comment by georgd** [comment]
Dear Frank, thanks for bravely chasing all those monsters :)

I'm not in a hurry as I still can use the old version and I think, I still
know how to compile the abbrevs from source for directly implanting them in
the Jurism folder.

Frank Bennett <notifications@github.com> schrieb am Mo., 17. Aug. 2020,
16:28:

> Well, that's interesting. The Mac build fails with a low-level "Can't find
> XPCOM" error, in both the beta and the release builds. The current release
> linked from the project site runs fine, so something has changed between
> then and now ... and this appears to be it:
>
>
> https://github.com/zotero/zotero-standalone-build/commit/32c50ad266ae3b21cb320575d74b9a20195fed4a
>
> zotero-standalone-build provides the stripped-down Firefox environment in
> which Zotero (and Jurism) runs. The note seems to be saying that to chase
> the latest Mac compatibility fixes, I'll need to build Firefox from scratch
> to obtain the Mac libraries. I've done that before (at the last major MacOS
> version threshold), and it takes something like six hours on my equipment.
> So ... this will happen, but it might not happen fast.
>
> On Mon, Aug 17, 2020 at 10:21 PM Frank Bennett <biercenator@gmail.com>
> wrote:
>
> > Oh, that's not good. The code was tested in the release branch, then
> > merged to beta when I realized that it needed to reside there. Should be
> > the same code, but I didn't do a trial to be sure it would run. Checking
> > now, more in a few minutes.
> >
> >
> > On Mon, Aug 17, 2020 at 10:12 PM Georg Mayr-Duffner <

**Comment by fbennett** [comment]
Actually ... from Dan's note there, it looks like there might be a
shortcut. Anyway, more on this tomorrow!

**Comment by fbennett** [comment]
Good morning. Good news and less good news. The good news is that the Big Sur operating system has not yet been released, so I can roll back the build repo to an earlier checkout and get this running. The less good news is that my Mac system, a late-2012 edition iMac, will not be supported by Big Sur. No idea whether it will be capable of building the Big-Sur-compatible release. If not, I'll either have to buy a Mac somewhere, or find someone with a later-model Mac to run the builds.

More in a bit ...

**Comment by fbennett** [comment]
I think this may be coming into focus. My old Mac was running Mojave, but it will run Catalina, and the upgrade has been queued for awhile. Among the recent Zotero changes to ``zotero-standalone-build`` was an adjustment to or addition of a script ``fetch_mar_tools``. Those are Firefox-specific tools for manipulating binary images. What I think happened is that I ran the script, updating from the tools I had built from scratch a few years ago to the Zotero-supplied binary copies. And those were almost certainly compiled to work with Catalina. I now have a system upgrade in progress: update to Catalina, followed by installation of the XCode development environment, followed by an update to compilers and whatnot that depend on it. The XCode update is particularly slow,  but now in progress. Fingers crossed, but I hope to have a working Mac beta for you soon. We live in hope.

**Comment by fbennett** [comment]
(The Big-Sur-libraries issue I noted above can't be what is breaking things, because the existing 5.0.90m2 release was built on a version of ``zotero-standalone-build`` that included that Zotero commit. Hence by process of elimination, the evil eye falls on a mismatch between the ``mar`` tools on the OS.)

**Comment by georgd** [comment]
If necessary, I can get acquainted with building it on my mac so I could jump in once I have Big Sur installed. However, I don’t think I’ll upgrade before official release.

**Comment by fbennett** [comment]
I have posted a query to the zotero-dev list, suggesting that maybe the
problem is a hardware incompatibility between the Big Sur libraries and my
late-2012 machine. I'll test that tomorrow by building a Zotero-patched
version of Firefox 69.0.9esr and using that for a beta build attempt. If
that works, we'll know that cross-compiling for Big Sur on this older
hardware is not possible---but it would also clarify the source of today's
repeated build failures, which is more important than anything at the
moment.

**Comment by fbennett** [comment]
Dear Georg: The beta release is now available. The link (uncorrupted this time) is https://our.law.nagoya-u.ac.jp/jurism/dl?channel=beta&platform=mac

The problem had nothing to do with Big Sur, and nothing to do with Zotero. It was caused by a stupid misstep on my part in the build process for the beta client on that particular machine. After hitting the zotero-dev list with a string of off-the-money questions to Dan, I followed up with an account of the mistakes I had made.

Reinstalling from the link should give you a working copy of the beta for review.

**Comment by georgd** [comment]
Dear Frank, thanks for your work. It’s indeed working now.

**Comment by fbennett** [comment]
Yay! Will queue it for the next release. Sorry a out the confusion over the
beta. It was a positive learning experience for me. :-)

Various household errands today, but I'll get to your other posts a bit
later on.

**Comment by georgd** [comment]
Oh, I hope no more centipede chasing. I looked up Japanese centipede and found some really frightening stories about that ōmukade species.

**Pull request closed without merging**
