### PR TITLE
Reworked Canada

### PR DESCRIPTION
**Pull request by Droitslinguistiques**
I added a lot of courts, abbrev and ABBREV, as well as a ca-fr variant for french abbreviations.

I'm still struggling with the federal level ABBREVs. The federal courts (Supreme, Federal, Federal Appeal, Tax and Martial) have different neutral citation identifiers based on whether the french or english version of the jugement is being cited. I couldn't figure out how to account for this.

### CODE REVIEW

**Comment by fbennett** [comment]
Thanks for this! I'll take a look tomorrow and write back with any comments. Meanwhile, though, about multilingual forms ...

If courts should be written all-English or all-French, we can generate separate abbreviation sets for each, and select the desired form in the style. The logic of it isn't fully documented yet, but registering the names in a single ``juris-ca-desc.json`` description file as you have done is correct. Details tomorrow (it's late here, and I should write when fresh).

**Comment by Droitslinguistiques** [comment]
Thank you! I was hoping to write a CSL-M McGill v9 french style, but I realised that I am way over my head. This contribution is much more within my skill levels. 

One other thing I also couldn't figure out is if there is a way to create a french variant of the "name" variable for courts and jurisdiction, so that it displays in french when Juris-M's interface is set to french.

**Comment by Droitslinguistiques** [comment]
One more comment : 

If there is a possibility of having language variants on the "name" and "ABBREV" variables, then it would change the structure of this for me, as it would free up the "abbrev" variable that I used for neutral citation language variants.

For exemple, with the stuff I saw in the docs, I had to create seven different "Supreme Court" courts:

Jurisdiction : Court name - ABBREV

- CA : Supreme Court of Canada - SC (en) or (CS) fr
- BC and NS : Supreme Court of "Province" - SC (no french)
- NL : Supreme Court of "juridiction name", Court of Appeal - CA
- NL : Supreme Court of "juridiction name", Trial Division - TD
- PE : Supreme Court, Appeal Division : CA
- PE : Supreme Court, Trial Divison : SC
- YU : Supreme Court of the "juridiction" territory : SC  

So, taking that list as exemple, I need to be able to have a french variant for the Canada supreme court. I also need to have the vendor neutral code "SC, CS, CA or TD" depending on the jurisdiction and the language. Finally, for three of them, the jurisdiction name is supposed to be in the middle of the court name, which gets even more complicated because in french, "Supreme Court of the Yukon territory" becomes "Cour suprême du térritoire du Yukon", meaning that in english the jurisdiction is in the middle of the court name, but it is at the end in french. 

I realize that this may not be the clairest explanation, which is why I've attached to this comment a PDF, showing you the standard french and english abbreviations for each court, followed in the last few pages by the english neutral citations and then the french neutral citations. _**There is an error on page 9. For New Brunswick's Queen Bench Court, in french, the neutral citation is NBBR, nor NBQB.**_


[F - Appendix B  Courts and Tribunals  Cours et tribunaux.pdf](https://github.com/Juris-M/legal-resource-registry/files/5065302/F.-.Appendix.B.Courts.and.Tribunals.Cours.et.tribunaux.pdf)

**Comment by fbennett** [comment]
Just a note to say that it may take a few days for me to respond properly. I'm working on a change to the Jurism infrastructure to properly reflect style updates in clients in the field, which requires considerable refactoring of some old code. I will get back though---and if you don't see a response within a week, feel free to ping back. Support for Canadian references is important.

**Comment by fbennett** [comment]
Back again! I took a look through the changes and your notes. I think I understand the issues, but it might be useful to have a chat before digging deeper into Canadian support. Is video possible at your end, or would you prefer to proceed here?

**Comment by Droitslinguistiques** [comment]
Video call would definitely be possible, and would probably make it easier to explain what I mean.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by georgd** [comment]
I’m very interested in the outcome of your meeting. Solving this issue for Canada will probably solve it for all countries and international bodies with multiple official languages (Switzerland, Belgium, Spain, EU,...)

**Comment by fbennett** [comment]
@Droitslinguistiques Let's see if we can set up a time for video call. It looks like any time between 18:00 and 21:00 (Toronto time) would work at this end. I'm generally free, if you pick a date I can send you an invite.

**Comment by Droitslinguistiques** [comment]
18h00 works for me, how about tomorrow? I'm also free any other night this week, so if another time works better, that's ok with me.

I'll draft up a document outlining the particulars of Canada's court naming conventions, and we can discuss what can be supported and how.

Looking forward to it!

**Comment by fbennett** [comment]
Sounds good, see you in ~24 hours. We'll need a channel to swap IDs. I can
post my mail here, or you can DM me on Twitter @fgbjr.

Frank

**Comment by Droitslinguistiques** [comment]
Sounds good. I don't really use twitter, but I reached out.

**Comment by Droitslinguistiques** [comment]
Sounds good. I just reached out over on Twitter.

**Comment by fbennett** [comment]
Lengthy post about revision work coming soon.

**Comment by Droitslinguistiques** [comment]
Very exciting news.

I made a lot more modifications about our call, so I should probably close this pull request and open a new one later right?

**Comment by fbennett** [comment]
@Droitslinguistiques If you have a file in the old format with your changes, it can be converted with the (new) ``-c`` option to the ``jurisupdate`` script, available after today's checkins to the repo.

**Comment by fbennett** [comment]
I have downloaded the original of your revised file, converted it to the new format, and merge it to the repo at https://github.com/Juris-M/legal-resource-registry/commit/3bf319bb149281cc08352795e45275f9842c0a9b. Thanks!

**Comment by fbennett** [comment]
I've updated the [README](https://github.com/juris-m/legal-resource-registry#jurism-legal-resource-registry) for the LRR to reflect the new format.

**Pull request closed without merging**
